name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  check-translations:
    name: Check Translations
    # Linux is required since this is a docker container action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: check_translations
        uses: ashutoshgngwr/android-translations@v1
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
